openapi: "3.0.0"
info:
  title: "ThrivioHR Users API"
  version: "0.1.0"
paths:
  /auth/login:
    post:
      summary: "User login"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [orgId, email]
              properties:
                orgId: { type: string, format: uuid }
                email: { type: string, format: email }
      responses:
        "200":
          description: "Login successful"
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken: { type: string }
                  refreshToken: { type: string }
                  user:
                    $ref: "#/components/schemas/UserPublic"
components:
  schemas:
    UserPublic:
      type: object
      properties:
        id: { type: string, format: uuid }
        organizationId: { type: string, format: uuid }
        email: { type: string, format: email }
        firstName: { type: string, nullable: true }
        lastName: { type: string, nullable: true }
        displayName: { type: string, nullable: true }